POST http://localhost:8000/submitstar
Content-Type: application/json

{
  "address": "1HZwkjkeaoZfTSaJxDw6aKkxp45agDiEzN",
  "message": "1HZwkjkeaoZfTSaJxDw6aKkxp45agDiEzN:1623362714:starRegistry",
  "signature": "HPNMrNtIGipy+FFxmcnlj2tKleVm5dOS/q+ibpsTzX/UhuQkBr2ITHbmWhwaao5UQvz/nQjPKCAEJZw71sEcYS8=",
  "star": {
    "data": "second best start in universe",
    "owner": "wildbill"
  }
}

